force-app/main/default/objects/Country_Info__c/Country_Info__c.object-meta.xml
<CustomObject>
    <label>Country Info</label>
    <nameField>
        <label>Country</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries Info</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Country_Info__c/fields/ISO_Alpha2__c.field-meta.xml
<CustomField>
    <fullName>ISO_Alpha2__c</fullName>
    <externalId>true</externalId>
    <label>ISO Alpha-2</label>
    <length>2</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Lead/fields/Country_Info__c.field-meta.xml
<CustomField>
    <fullName>Country_Info__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Country Info</label>
    <referenceTo>Country_Info__c</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/LeadTriggerTest.cls
@isTest
public class LeadTriggerTest {
    @TestSetup
    static void makeData(){
        Test.setMock(HttpCalloutMock.class, new CountrylayerCalloutMock());
        Test.startTest();
        CountrylayerCallout.makeCallout();
        Test.stopTest();
    }

    @isTest
    public static void testInsert(){
        Country_Info__c cInf = [select Id from Country_Info__c where ISO_Alpha2__c = 'IE'];

        Lead ld = new Lead(FirstName='Molly',LastName='Malone',Company='Cockles&Mussels',CountryCode='IE');
        Test.startTest();
        insert ld;
        Test.stopTest();

        Lead ldResult = [select Country_Info__c from Lead where Id = :ld.Id];
        System.assertEquals(cInf.Id, ldResult.Country_Info__c);
    }

    @isTest
    public static void testUpdate(){
        Country_Info__c cInf = [select Id from Country_Info__c where ISO_Alpha2__c = 'AF'];
        Lead ld = new Lead(FirstName='Molly',LastName='Malone',Company='Cockles&Mussels',CountryCode='IE');
        insert ld;

        Lead ldToUpdate = [select Id, CountryCode from Lead where Id = :ld.Id];
        ldToUpdate.CountryCode = 'AF';
        Test.startTest();
        update ldToUpdate;
        Test.stopTest();

        Lead ldResult = [select Country_Info__c from Lead where Id = :ld.Id];
        System.assertEquals(cInf.Id, ldResult.Country_Info__c);
    }
}